version: '3.1'
services:
  database:
    image: postgres
    ports:
      - "28017:28017"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USERNAME=postgres
  web:
    image: zohoanalytics/onprem
    ports:
      - 8443:8443
